package fa.grubber;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Daniel' at '25.02.17 12:49' with Gradle 2.14.1
 *
 * @author Daniel, @date 25.02.17 12:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
