import org.junit.Test;

import fa.grubber.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Daniel' at '25.02.17 12:49' with Gradle 2.14.1
 *
 * @author Daniel, @date 25.02.17 12:49
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
